/* Generated by MyraPad at 09/04/2021 21:18:57 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

namespace UI
{
	partial class BrainEditor: Grid
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Inputs";

			var label2 = new Label();
			label2.Text = "Outputs";
			label2.GridColumn = 1;

			_inputList = new ListBox();
			_inputList.Id = "_inputList";

			var scrollViewer1 = new ScrollViewer();
			scrollViewer1.MaxHeight = 150;
			scrollViewer1.GridRow = 1;
			scrollViewer1.Content = _inputList;

			_outputList = new ListBox();
			_outputList.Id = "_outputList";

			var scrollViewer2 = new ScrollViewer();
			scrollViewer2.MaxHeight = 150;
			scrollViewer2.GridColumn = 1;
			scrollViewer2.GridRow = 1;
			scrollViewer2.Content = _outputList;

			_removeSelectedInput = new TextButton();
			_removeSelectedInput.Text = "Remove Selected";
			_removeSelectedInput.GridRow = 2;
			_removeSelectedInput.Id = "_removeSelectedInput";

			_removeSelectedOutput = new TextButton();
			_removeSelectedOutput.Text = "Remove Selected";
			_removeSelectedOutput.GridColumn = 1;
			_removeSelectedOutput.GridRow = 2;
			_removeSelectedOutput.Id = "_removeSelectedOutput";

			_addInputButton = new TextButton();
			_addInputButton.Text = "Add Input";
			_addInputButton.GridRow = 3;
			_addInputButton.Id = "_addInputButton";

			_addOutputButton = new TextButton();
			_addOutputButton.Text = "Add Output";
			_addOutputButton.GridColumn = 1;
			_addOutputButton.GridRow = 3;
			_addOutputButton.Id = "_addOutputButton";

			
			ShowGridLines = true;
			ColumnSpacing = 8;
			RowSpacing = 8;
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			Widgets.Add(label1);
			Widgets.Add(label2);
			Widgets.Add(scrollViewer1);
			Widgets.Add(scrollViewer2);
			Widgets.Add(_removeSelectedInput);
			Widgets.Add(_removeSelectedOutput);
			Widgets.Add(_addInputButton);
			Widgets.Add(_addOutputButton);
		}

		
		public ListBox _inputList;
		public ListBox _outputList;
		public TextButton _removeSelectedInput;
		public TextButton _removeSelectedOutput;
		public TextButton _addInputButton;
		public TextButton _addOutputButton;
	}
}
