/* Generated by MyraPad at 09/04/2021 20:22:14 */
using Myra.Graphics2D.UI;
using SoupV2.Simulation.Components;

namespace UI
{
	public partial class BrainEditor
	{
		public BrainEditor(BrainComponent component)
		{
			BuildUI();

			foreach (string input in component.InputMap.Values)
            {
				var item = new ListItem(input);
				_inputList.Items.Add(item);
            }

			foreach (string output in component.OutputMap.Values)
			{
				var item = new ListItem(output);
				_outputList.Items.Add(item);
			}
		}
	}
}