/* Generated by MyraPad at 08/04/2021 18:44:12 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

namespace UI
{
	partial class DbConnectUI: Grid
	{
		private void BuildUI()
		{
			_ipLabel = new Label();
			_ipLabel.Text = "IP Address:";
			_ipLabel.Id = "_ipLabel";

			_ipAddressInput = new TextBox();
			_ipAddressInput.Text = "localhost";
			_ipAddressInput.MinWidth = 150;
			_ipAddressInput.GridColumn = 1;
			_ipAddressInput.Id = "_ipAddressInput";

			_portLabel = new Label();
			_portLabel.Text = "Port:";
			_portLabel.GridRow = 1;
			_portLabel.Id = "_portLabel";

			_portInput = new TextBox();
			_portInput.Text = "27017";
			_portInput.MinWidth = 150;
			_portInput.GridColumn = 1;
			_portInput.GridRow = 1;
			_portInput.Id = "_portInput";

			_usernameLabel = new Label();
			_usernameLabel.Text = "Username:";
			_usernameLabel.GridRow = 2;
			_usernameLabel.Id = "_usernameLabel";

			_usernameInput = new TextBox();
			_usernameInput.Text = "username";
			_usernameInput.MinWidth = 150;
			_usernameInput.GridColumn = 1;
			_usernameInput.GridRow = 2;
			_usernameInput.Id = "_usernameInput";

			_passwordLabel = new Label();
			_passwordLabel.Text = "Password:";
			_passwordLabel.GridRow = 3;
			_passwordLabel.Id = "_passwordLabel";

			_passwordInput = new TextBox();
			_passwordInput.PasswordField = true;
			_passwordInput.MinWidth = 150;
			_passwordInput.GridColumn = 1;
			_passwordInput.GridRow = 3;
			_passwordInput.Id = "_passwordInput";

			_connectButton = new TextButton();
			_connectButton.Text = "Connect";
			_connectButton.GridRow = 4;
			_connectButton.Id = "_connectButton";

			_statusLabel = new Label();
			_statusLabel.Text = "Status:";
			_statusLabel.MinWidth = 150;
			_statusLabel.GridColumn = 1;
			_statusLabel.GridRow = 4;
			_statusLabel.Id = "_statusLabel";

			_backButton = new TextButton();
			_backButton.Text = "Back";
			_backButton.GridRow = 5;
			_backButton.Id = "_backButton";

			
			ShowGridLines = true;
			ColumnSpacing = 8;
			RowSpacing = 8;
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Widgets.Add(_ipLabel);
			Widgets.Add(_ipAddressInput);
			Widgets.Add(_portLabel);
			Widgets.Add(_portInput);
			Widgets.Add(_usernameLabel);
			Widgets.Add(_usernameInput);
			Widgets.Add(_passwordLabel);
			Widgets.Add(_passwordInput);
			Widgets.Add(_connectButton);
			Widgets.Add(_statusLabel);
			Widgets.Add(_backButton);
		}

		
		public Label _ipLabel;
		public TextBox _ipAddressInput;
		public Label _portLabel;
		public TextBox _portInput;
		public Label _usernameLabel;
		public TextBox _usernameInput;
		public Label _passwordLabel;
		public TextBox _passwordInput;
		public TextButton _connectButton;
		public Label _statusLabel;
		public TextButton _backButton;
	}
}
