///* Generated by MyraPad at 08/04/2021 17:48:33 */
//using SoupV2;
//using SoupV2.DB;

//namespace UI
//{
//	public partial class DbConnectUI
//	{
//		public DbConnectUI(Soup soup)
//		{
//			BuildUI();

//			_ipAddressInput.Text = SoupMongo.IP;
//			_portInput.Text = SoupMongo.Port;
//			_usernameInput.Text = SoupMongo.Username;
//			_passwordInput.Text = SoupMongo.Password;

//			_backButton.Click += (s, a) =>
//			{
//				Desktop.Root = new MainMenuUI(soup);
//			};

//			_connectButton.Click += (s, a) =>
//			{
//				SoupMongo.IP = _ipAddressInput.Text;
//				SoupMongo.Port = _portInput.Text;
//				SoupMongo.Username = _usernameInput.Text;
//				SoupMongo.Password = _passwordInput.Text;

//				var (connected, reason) = SoupMongo.Connect();
//				_statusLabel.Text = $"Status: {reason}";
//			};
//		}
//	}
//}