/* Generated by MyraPad at 09/04/2021 15:05:51 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

namespace UI
{
	partial class EntityEditWidget: Grid
	{
		private void BuildUI()
		{
			_tagTextBox = new TextBox();
			_tagTextBox.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_tagTextBox.MinWidth = 150;
			_tagTextBox.Id = "_tagTextBox";

			_setTagButton = new TextButton();
			_setTagButton.Text = "Set Tag";
			_setTagButton.GridColumn = 1;
			_setTagButton.Id = "_setTagButton";

			_addComponentButton = new TextButton();
			_addComponentButton.Text = "Add Component...";
			_addComponentButton.GridRow = 1;
			_addComponentButton.Id = "_addComponentButton";

			_removeComponentButton = new TextButton();
			_removeComponentButton.Text = "Remove Component...";
			_removeComponentButton.GridColumn = 1;
			_removeComponentButton.GridRow = 1;
			_removeComponentButton.Id = "_removeComponentButton";

			_deleteEntityButton = new TextButton();
			_deleteEntityButton.Text = "Delete Entity";
			_deleteEntityButton.GridRow = 2;
			_deleteEntityButton.Id = "_deleteEntityButton";

			_addChildButton = new TextButton();
			_addChildButton.Text = "Add Child";
			_addChildButton.GridColumn = 1;
			_addChildButton.GridRow = 2;
			_addChildButton.Id = "_addChildButton";

			
			ColumnSpacing = 8;
			RowSpacing = 8;
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			BorderThickness = new Thickness(8);
			Widgets.Add(_tagTextBox);
			Widgets.Add(_setTagButton);
			Widgets.Add(_addComponentButton);
			Widgets.Add(_removeComponentButton);
			Widgets.Add(_deleteEntityButton);
			Widgets.Add(_addChildButton);
		}

		
		public TextBox _tagTextBox;
		public TextButton _setTagButton;
		public TextButton _addComponentButton;
		public TextButton _removeComponentButton;
		public TextButton _deleteEntityButton;
		public TextButton _addChildButton;
	}
}
