/* Generated by MyraPad at 09/04/2021 11:05:21 */
using EntityComponentSystem;
using Myra.Graphics2D.UI;
using SoupV2.UI;

namespace UI
{
	public partial class EntityEditWidget
	{
		public EntityEditWidget(Entity target, EntityEditor editor)
		{
			BuildUI();

			if(target.Parent is null)
            {
				_deleteEntityButton.Enabled = false;
            }

			_tagTextBox.Text = target.Tag;

			_setTagButton.Click += (s, a) =>
			{
				var newTag = _tagTextBox.Text;
				string oldTag = target.Tag;

				if (!(target.Parent is null))
                {
					foreach ((string key, Entity entity) in target.Parent.Children)
					{
						if (key == newTag)
						{
							ErrorBox box = new ErrorBox("Duplicate tag. Children of a parent must have a unique tag.", null);

							box.ShowModal(Desktop);
							return;
						}
					}
					target.Parent.Children.Remove(oldTag);
					target.Parent.Children.Add(newTag, target);
                }
				target.Tag = newTag;
				editor.RebuildTree();

			};
		}
	}
}