/* Generated by MyraPad at 09/04/2021 11:41:55 */
namespace UI
{
	public partial class ErrorBox
	{
		public ErrorBox(string text, string title = "Error")
		{
			BuildUI();
			Title = title;
			_message.Text = text;
		}
	}
}