/* Generated by MyraPad at 09/04/2021 11:43:32 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

namespace UI
{
	partial class ErrorBox: Window
	{
		private void BuildUI()
		{
			_message = new Label();
			_message.Id = "_message";

			
			Title = "Error";
			Left = 676;
			Top = 205;
			Id = "_errorWindow";
			Content = _message;
		}

		
		public Label _message;
	}
}
