/* Generated by MyraPad at 11/04/2021 15:57:26 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

namespace UI
{
	partial class ExperimentSetUpUI: Grid
	{
		private void BuildUI()
		{
			_loadSettingsButton = new TextButton();
			_loadSettingsButton.Text = "Load Settings";
			_loadSettingsButton.Id = "_loadSettingsButton";

			_saveSettingsButton = new TextButton();
			_saveSettingsButton.Text = "Save Settings";
			_saveSettingsButton.GridColumn = 1;
			_saveSettingsButton.Id = "_saveSettingsButton";

			_editSettingsButton = new TextButton();
			_editSettingsButton.Text = "Edit Settings";
			_editSettingsButton.GridRow = 1;
			_editSettingsButton.Id = "_editSettingsButton";

			_saveExperimentLabel = new Label();
			_saveExperimentLabel.Text = "Statistics Output:";
			_saveExperimentLabel.GridRow = 2;
			_saveExperimentLabel.Id = "_saveExperimentLabel";

			_settingsDestinationComboBox = new ComboBox();
			_settingsDestinationComboBox.GridColumn = 1;
			_settingsDestinationComboBox.GridRow = 2;
			_settingsDestinationComboBox.Id = "_settingsDestinationComboBox";

			_browseFileButton = new TextButton();
			_browseFileButton.Text = "Browse File";
			_browseFileButton.GridRow = 3;
			_browseFileButton.Id = "_browseFileButton";

			_currentFilePathLabel = new Label();
			_currentFilePathLabel.GridColumn = 1;
			_currentFilePathLabel.GridRow = 3;
			_currentFilePathLabel.Id = "_currentFilePathLabel";

			_beginButton = new TextButton();
			_beginButton.Text = "Start Experiment";
			_beginButton.GridColumn = 1;
			_beginButton.GridRow = 4;
			_beginButton.Id = "_beginButton";

			_backButton = new TextButton();
			_backButton.Text = "Back";
			_backButton.GridRow = 4;
			_backButton.Id = "_backButton";

			var grid1 = new Grid();
			grid1.ShowGridLines = true;
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 8;
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			grid1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			grid1.Widgets.Add(_loadSettingsButton);
			grid1.Widgets.Add(_saveSettingsButton);
			grid1.Widgets.Add(_editSettingsButton);
			grid1.Widgets.Add(_saveExperimentLabel);
			grid1.Widgets.Add(_settingsDestinationComboBox);
			grid1.Widgets.Add(_browseFileButton);
			grid1.Widgets.Add(_currentFilePathLabel);
			grid1.Widgets.Add(_beginButton);
			grid1.Widgets.Add(_backButton);

			
			ColumnSpacing = 8;
			RowSpacing = 8;
			HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Widgets.Add(grid1);
		}

		
		public TextButton _loadSettingsButton;
		public TextButton _saveSettingsButton;
		public TextButton _editSettingsButton;
		public Label _saveExperimentLabel;
		public ComboBox _settingsDestinationComboBox;
		public TextButton _browseFileButton;
		public Label _currentFilePathLabel;
		public TextButton _beginButton;
		public TextButton _backButton;
	}
}
