///* Generated by MyraPad at 08/04/2021 17:52:51 */
//using SoupV2;
//using SoupV2.UI;

//namespace UI
//{
//	public partial class MainMenuUI
//	{
//		public MainMenuUI(Soup soup)
//		{
//			BuildUI();

//			_connectToDb.Selected += (s, a) => {
//				Desktop.Root = new DbConnectUI(soup);
//			};

//			_beginSimulation.Selected += (s, a) => {
//				Desktop.Root = new ExperimentSetUpUI(soup);
//			};

//			_entityEditor.Selected += (s, a) =>
//			{
//				Desktop.Root = new EntityEditor(soup);
//			};


//		}
//	}
//}