/* Generated by MyraPad at 23/03/2021 18:41:23 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

namespace SoupV2.UI
{
	partial class MainUI: Panel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Soup";
			label1.TextColor = ColorStorage.CreateColor(254, 57, 48, 255);
			label1.DisabledTextColor = ColorStorage.CreateColor(64, 64, 64, 255);
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			_menuLoadScenario = new MenuItem();
			_menuLoadScenario.Text = "Load Scenario";
			_menuLoadScenario.Id = "_menuLoadScenario";

			_newScenario = new MenuItem();
			_newScenario.Text = "New Scenario";
			_newScenario.Id = "_newScenario";

			_quit = new MenuItem();
			_quit.Text = "Quit";
			_quit.Id = "_quit";

			var verticalMenu1 = new VerticalMenu();
			verticalMenu1.Background = new SolidBrush("#404040FF");
			verticalMenu1.Items.Add(_menuLoadScenario);
			verticalMenu1.Items.Add(_newScenario);
			verticalMenu1.Items.Add(_quit);

			var grid1 = new Grid();

			var horizontalSlider1 = new HorizontalSlider();
			horizontalSlider1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			horizontalSlider1.MinWidth = 200;

			var label2 = new Label();
			label2.Text = "Game Speed";
			label2.TextColor = ColorStorage.CreateColor(254, 57, 48, 255);
			label2.DisabledTextColor = ColorStorage.CreateColor(64, 64, 64, 255);
			label2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			var panel1 = new Panel();
			panel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			panel1.MinWidth = 100;
			panel1.Border = new SolidBrush("#5BC6FAFF");
			panel1.Widgets.Add(horizontalSlider1);
			panel1.Widgets.Add(label2);

			
			Widgets.Add(label1);
			Widgets.Add(verticalMenu1);
			Widgets.Add(grid1);
			Widgets.Add(panel1);
		}

		
		public MenuItem _menuLoadScenario;
		public MenuItem _newScenario;
		public MenuItem _quit;
	}
}
