///* Generated by MyraPad at 08/04/2021 20:09:57 */
//using Myra;
//using Myra.Graphics2D;
//using Myra.Graphics2D.TextureAtlases;
//using Myra.Graphics2D.UI;
//using Myra.Graphics2D.Brushes;
//using Myra.Graphics2D.UI.Properties;

//#if MONOGAME || FNA
//using Microsoft.Xna.Framework;
//using Microsoft.Xna.Framework.Graphics;
//#elif STRIDE
//using Stride.Core.Mathematics;
//#else
//using System.Drawing;
//using System.Numerics;
//#endif

//namespace UI
//{
//	partial class MainMenuUI: Panel
//	{
//		private void BuildUI()
//		{
//			_connectToDb = new MenuItem();
//			_connectToDb.Text = "Connect to Database";
//			_connectToDb.Id = "_connectToDb";

//			_beginSimulation = new MenuItem();
//			_beginSimulation.Text = "Begin Simulation";
//			_beginSimulation.Id = "_beginSimulation";

//			_entityEditor = new MenuItem();
//			_entityEditor.Text = "Entity Editor";
//			_entityEditor.Id = "_entityEditor";

//			_quit = new MenuItem();
//			_quit.Text = "Quit";
//			_quit.Id = "_quit";

//			var verticalMenu1 = new VerticalMenu();
//			verticalMenu1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
//			verticalMenu1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
//			verticalMenu1.Background = new SolidBrush("#404040FF");
//			verticalMenu1.Items.Add(_connectToDb);
//			verticalMenu1.Items.Add(_beginSimulation);
//			verticalMenu1.Items.Add(_entityEditor);
//			verticalMenu1.Items.Add(_quit);

			
//			Widgets.Add(verticalMenu1);
//		}

		
//		public MenuItem _connectToDb;
//		public MenuItem _beginSimulation;
//		public MenuItem _entityEditor;
//		public MenuItem _quit;
//	}
//}
